import { ArrowUpRight } from "lucide-react";

import { adminPaths } from "../app/routePaths.js";
import { AdminPageHeader } from "../components/layout/AdminPageHeader.jsx";
import { Button } from "../components/ui/Button.jsx";
import { DataTable } from "../components/ui/DataTable.jsx";
import { MetricCard, Panel, StatusBadge } from "../components/ui/AdminPrimitives.jsx";
import { demoChartPoints, demoMetrics, demoOrders } from "../fixtures/adminFixtures.js";

export function DashboardPage() {
  return <><AdminPageHeader eyebrow="Monday · fixture view" title="Good afternoon." description="A static operational dashboard demonstrates layout only. No metric is calculated from orders or payments." actions={<Button to={adminPaths.menu} variant="secondary">View menu shell <ArrowUpRight className="size-4" /></Button>} /><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{demoMetrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><Panel className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Revenue</p><h2 className="mt-2 text-xl font-semibold text-brand-950">Sales trend placeholder</h2></div><StatusBadge>30 days · static</StatusBadge></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-l border-line px-3 pt-6" aria-label="Static chart placeholder">{demoChartPoints.map((point, index) => <div key={`${point}-${index}`} className="flex-1 rounded-t bg-brand-700/75" style={{ height: `${point}%` }} />)}</div><p className="mt-3 text-xs text-muted">No Recharts or analytics logic is implemented.</p></Panel><Panel className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Quick actions</p><h2 className="mt-2 text-xl font-semibold text-brand-950">Run the store</h2><div className="mt-5 grid divide-y divide-line">{[{ label: "Review orders", path: adminPaths.orders }, { label: "Delivery pricing", path: adminPaths.delivery }, { label: "Checkout settings", path: adminPaths.settings }].map((item) => <Button key={item.path} to={item.path} variant="ghost" className="justify-between rounded-none px-0">{item.label}<ArrowUpRight className="size-4" /></Button>)}</div></Panel></div><div className="mt-6"><DataTable caption="Recent demo orders" columns={["Order", "Customer", "Total", "Payment", "Status"]} rows={demoOrders} renderRow={(order) => <tr key={order.id}><td className="px-4 py-4 text-sm font-semibold text-brand-950">{order.id}</td><td className="px-4 py-4 text-sm text-muted">{order.customer}</td><td className="px-4 py-4 text-sm font-semibold">{order.total}</td><td className="px-4 py-4 text-sm text-muted">{order.payment} · {order.method}</td><td className="px-4 py-4"><StatusBadge tone={order.tone}>{order.status}</StatusBadge></td></tr>} /></div></>;
}
