import { AdminPageHeader } from "../components/layout/AdminPageHeader.jsx";
import { Panel, StatusBadge } from "../components/ui/AdminPrimitives.jsx";
import { Button } from "../components/ui/Button.jsx";
import { demoFeedback } from "../fixtures/adminFixtures.js";

export function FeedbackPage() {
  const selected = demoFeedback[0];
  return <><AdminPageHeader eyebrow="Private inbox foundation" title="Feedback" description="Fixture inbox/detail layout. No private feedback records are read in Cycle 1." /><div className="mt-6 grid gap-6 lg:grid-cols-[20rem_minmax(0,1fr)]"><Panel className="divide-y divide-line">{demoFeedback.map((item, index) => <button type="button" key={item.id} className={`w-full p-4 text-left hover:bg-brand-100 ${index === 0 ? "bg-brand-100/60" : ""}`}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-brand-950">{item.subject}</p><StatusBadge tone={item.status === "Unread" ? "warning" : "neutral"}>{item.status}</StatusBadge></div><p className="mt-2 text-xs text-muted">{item.name} · {item.id}</p></button>)}</Panel><Panel className="p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-700">{selected.id}</p><h2 className="mt-2 text-2xl font-semibold text-brand-950">{selected.subject}</h2></div><StatusBadge tone="warning">Private fixture</StatusBadge></div><dl className="mt-6 grid gap-4 border-y border-line py-5 sm:grid-cols-2"><div><dt className="text-xs text-muted">Sender</dt><dd className="mt-1 text-sm font-semibold">{selected.name}</dd></div><div><dt className="text-xs text-muted">Rating</dt><dd className="mt-1 text-sm font-semibold">{selected.rating}</dd></div></dl><p className="mt-6 max-w-2xl text-sm leading-7 text-muted">This is deliberately fabricated content. Anonymous feedback submission, private admin access, filters, and testimonial conversion begin in Cycle 17 after security boundaries exist.</p><Button className="mt-6" disabled>Actions unavailable in Cycle 1</Button></Panel></div></>;
}
