import { LockKeyhole, Sprout } from "lucide-react";

import { adminPaths } from "../app/routePaths.js";
import { Button } from "../components/ui/Button.jsx";
import { TextInput } from "../components/ui/FormControls.jsx";

export function LoginPage() {
  return <main className="grid min-h-screen bg-canvas lg:grid-cols-[0.9fr_1.1fr]"><section className="flex flex-col justify-between bg-brand-950 p-8 text-white sm:p-12 lg:p-16"><div className="flex items-center gap-2"><Sprout className="size-6 text-green-300" /><span className="font-display text-3xl font-bold">nuede</span></div><div className="my-16 max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-green-300">Admin console</p><h1 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Calm tools for a busy kitchen.</h1><p className="mt-6 max-w-lg text-base leading-8 text-white/70">This is the visual login shell. Authentication, sessions, roles, and route protection begin in Cycle 3.</p></div><p className="text-xs text-white/50">Independent Nuede administration application</p></section><section className="grid place-items-center p-5 sm:p-8"><div className="w-full max-w-md rounded-dialog border border-line bg-surface p-6 sm:p-8"><div className="grid size-12 place-items-center rounded-full bg-brand-100 text-brand-700"><LockKeyhole className="size-5" /></div><h2 className="mt-6 text-3xl font-semibold text-brand-950">Welcome back</h2><p className="mt-2 text-sm leading-6 text-muted">Enter demo values to inspect control styling. Nothing is submitted.</p><form className="mt-7 grid gap-5" onSubmit={(event) => event.preventDefault()}><TextInput label="Email address" type="email" autoComplete="email" placeholder="admin@example.com" required /><TextInput label="Password" type="password" autoComplete="current-password" placeholder="Enter password" help="Supabase Auth is not connected." required /><Button to={adminPaths.dashboard} className="w-full">Open dashboard shell</Button></form><p className="mt-5 text-center text-xs leading-5 text-muted">This navigation is not authentication and provides no authorization.</p></div></section></main>;
}
