import { formatKobo } from "@nuede/domain/currency";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";

import { EmptyState } from "../../../components/ui/FeedbackStates.jsx";
import { Panel } from "../../../components/ui/AdminPrimitives.jsx";
import { chartMoneyValue, formatChartKobo, paymentMethodLabel } from "../utils/analyticsUtils.js";

const COLORS = ["#096e21", "#956515", "#173323", "#667369"];

export function PaymentMixChart({ rows = [] }) {
  if (!rows.length) return <EmptyState title="No payment mix in this period" message="Payment shares will appear after an eligible payment is verified." />;
  const data = rows.map((row) => ({ ...row, label: paymentMethodLabel(row.payment_method), value: chartMoneyValue(row.revenue_kobo) }));
  return <Panel className="min-w-0 p-5 sm:p-6" aria-labelledby="payment-mix-title"><h2 id="payment-mix-title" className="text-lg font-semibold text-brand-950">Payment method mix</h2><p className="mt-1 text-sm text-muted">Share of verified revenue by canonical payment method.</p><div className="mt-3 h-52" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="label" innerRadius="55%" outerRadius="82%" paddingAngle={2}>{data.map((row, index) => <Cell key={row.payment_method} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip formatter={(value) => formatChartKobo(value)} /></PieChart></ResponsiveContainer></div><ul className="grid gap-3" aria-label="Payment method revenue breakdown">{data.map((row, index) => <li key={row.payment_method} className="flex items-center justify-between gap-4 text-sm"><span className="flex items-center gap-2 font-semibold text-brand-950"><span className="size-3 rounded-sm" style={{ backgroundColor: COLORS[index % COLORS.length] }} aria-hidden="true" />{row.label}</span><span className="text-right"><span className="font-semibold">{formatKobo(row.revenue_kobo)}</span><span className="ml-2 text-muted">{Number(row.revenue_share_percent || 0).toLocaleString("en-NG", { maximumFractionDigits: 1 })}%</span></span></li>)}</ul></Panel>;
}

export function DeliveryZoneChart({ rows = [] }) {
  if (!rows.length) return <EmptyState title="No delivery-zone sales in this period" message="Zone performance will appear after an eligible paid order." />;
  const data = rows.slice(0, 8).map((row) => ({ ...row, value: chartMoneyValue(row.revenue_kobo) }));
  return <Panel className="min-w-0 p-5 sm:p-6" aria-labelledby="delivery-zone-title"><h2 id="delivery-zone-title" className="text-lg font-semibold text-brand-950">Delivery-zone performance</h2><p className="mt-1 text-sm text-muted">Verified revenue by purchase-time delivery-zone snapshot.</p><div className="mt-5 h-64" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: 8, right: 8 }}><CartesianGrid horizontal={false} stroke="#e2e7e1" /><XAxis type="number" tickFormatter={formatChartKobo} tick={{ fill: "#667369", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="delivery_zone_name" width={92} tick={{ fill: "#667369", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => formatChartKobo(value)} /><Bar dataKey="value" fill="#096e21" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[28rem] text-left text-sm"><caption className="sr-only">Delivery-zone exact totals</caption><thead><tr className="border-b border-line text-xs uppercase tracking-wide text-muted"><th className="py-2">Zone</th><th className="py-2 text-right">Orders</th><th className="py-2 text-right">Revenue</th><th className="py-2 text-right">Delivery fees</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.delivery_zone_id}-${row.delivery_zone_name}`} className="border-b border-line last:border-0"><td className="py-3 font-semibold text-brand-950">{row.delivery_zone_name}</td><td className="py-3 text-right">{row.paid_orders}</td><td className="py-3 text-right font-semibold">{formatKobo(row.revenue_kobo)}</td><td className="py-3 text-right text-muted">{formatKobo(row.delivery_fee_kobo)}</td></tr>)}</tbody></table></div></Panel>;
}
